/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package purplebox;

/**
 *
 * @author oxcom
 */
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class PurpleBoxGUI extends javax.swing.JFrame {
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form PurpleBoxGUI
     */
    public PurpleBoxGUI() {
        initComponents();
        conn = DataBaseConnector.ConnectDB();
        updateTable();
    }
    private void updateTable(){
        try{
            String SQL = "SELECT * FROM Movies";
            pst = conn.prepareStatement(SQL);
            rs = pst.executeQuery();
            MoviesTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
        try{
            String SQL = "SELECT * FROM Games";
            pst = conn.prepareStatement(SQL);
            rs = pst.executeQuery();
            GamesTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
        try{
            String SQL = "SELECT * FROM ShoppingCart";
            pst = conn.prepareStatement(SQL);
            rs = pst.executeQuery();
            ShoppingCartTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        PurpleBox = new javax.swing.JTabbedPane();
        Home = new java.awt.Panel();
        HomeMessage = new java.awt.Label();
        Movies = new java.awt.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MoviesTable = new javax.swing.JTable();
        AddToCartMovie = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextOutputMovies = new javax.swing.JTextArea();
        Games = new java.awt.Panel();
        jScrollPane3 = new javax.swing.JScrollPane();
        GamesTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextOutputGames = new javax.swing.JTextArea();
        AddToCartGame = new javax.swing.JButton();
        ShoppingCart = new java.awt.Panel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ShoppingCartTable = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        ShoppingCartOutput = new javax.swing.JTextArea();
        RemoveFromCart = new javax.swing.JButton();
        RemoveAll = new javax.swing.JButton();
        Checkout = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 153));
        setFocusableWindowState(false);
        setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        PurpleBox.setBackground(new java.awt.Color(76, 44, 118));
        PurpleBox.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        HomeMessage.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        HomeMessage.setForeground(new java.awt.Color(204, 204, 204));
        HomeMessage.setText("Welcome to Purple Box. Select a tab to get started renting your favorite games and movies!");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(HomeMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addGap(163, 163, 163))
        );

        PurpleBox.addTab("Home", Home);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, MoviesTable, org.jdesktop.beansbinding.ObjectProperty.create(), MoviesTable, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding.bind();
        jScrollPane2.setViewportView(MoviesTable);

        AddToCartMovie.setText("Add To Cart");
        AddToCartMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToCartMovieActionPerformed(evt);
            }
        });

        TextOutputMovies.setColumns(20);
        TextOutputMovies.setRows(5);
        jScrollPane1.setViewportView(TextOutputMovies);

        javax.swing.GroupLayout MoviesLayout = new javax.swing.GroupLayout(Movies);
        Movies.setLayout(MoviesLayout);
        MoviesLayout.setHorizontalGroup(
            MoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MoviesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MoviesLayout.createSequentialGroup()
                        .addComponent(AddToCartMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(499, 499, 499))
                    .addGroup(MoviesLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        MoviesLayout.setVerticalGroup(
            MoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MoviesLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddToCartMovie)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        PurpleBox.addTab("Movies", Movies);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, GamesTable, org.jdesktop.beansbinding.ObjectProperty.create(), GamesTable, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding.bind();
        jScrollPane3.setViewportView(GamesTable);

        TextOutputGames.setColumns(20);
        TextOutputGames.setRows(5);
        jScrollPane4.setViewportView(TextOutputGames);

        AddToCartGame.setText("Add To Cart");

        javax.swing.GroupLayout GamesLayout = new javax.swing.GroupLayout(Games);
        Games.setLayout(GamesLayout);
        GamesLayout.setHorizontalGroup(
            GamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamesLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(GamesLayout.createSequentialGroup()
                        .addComponent(AddToCartGame)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        GamesLayout.setVerticalGroup(
            GamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamesLayout.createSequentialGroup()
                .addComponent(jScrollPane4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddToCartGame)
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        PurpleBox.addTab("Games", Games);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, ShoppingCartTable, org.jdesktop.beansbinding.ObjectProperty.create(), ShoppingCartTable, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding.bind();
        jScrollPane5.setViewportView(ShoppingCartTable);

        ShoppingCartOutput.setColumns(20);
        ShoppingCartOutput.setRows(5);
        jScrollPane6.setViewportView(ShoppingCartOutput);

        RemoveFromCart.setText("Remove From Cart");
        RemoveFromCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveFromCartActionPerformed(evt);
            }
        });

        RemoveAll.setText("Remove All From Cart");

        Checkout.setText("Checkout");

        javax.swing.GroupLayout ShoppingCartLayout = new javax.swing.GroupLayout(ShoppingCart);
        ShoppingCart.setLayout(ShoppingCartLayout);
        ShoppingCartLayout.setHorizontalGroup(
            ShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShoppingCartLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(ShoppingCartLayout.createSequentialGroup()
                        .addGroup(ShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RemoveFromCart)
                            .addComponent(RemoveAll)
                            .addComponent(Checkout))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ShoppingCartLayout.setVerticalGroup(
            ShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
            .addGroup(ShoppingCartLayout.createSequentialGroup()
                .addComponent(jScrollPane6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RemoveFromCart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RemoveAll)
                .addGap(45, 45, 45)
                .addComponent(Checkout)
                .addContainerGap())
        );

        PurpleBox.addTab("Shopping Cart", ShoppingCart);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PurpleBox)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PurpleBox)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddToCartMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCartMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddToCartMovieActionPerformed

    private void RemoveFromCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveFromCartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveFromCartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurpleBoxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurpleBoxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurpleBoxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurpleBoxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurpleBoxGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCartGame;
    private javax.swing.JButton AddToCartMovie;
    private javax.swing.JButton Checkout;
    private java.awt.Panel Games;
    private javax.swing.JTable GamesTable;
    private java.awt.Panel Home;
    private java.awt.Label HomeMessage;
    private java.awt.Panel Movies;
    private javax.swing.JTable MoviesTable;
    private javax.swing.JTabbedPane PurpleBox;
    private javax.swing.JButton RemoveAll;
    private javax.swing.JButton RemoveFromCart;
    private java.awt.Panel ShoppingCart;
    private javax.swing.JTextArea ShoppingCartOutput;
    private javax.swing.JTable ShoppingCartTable;
    private javax.swing.JTextArea TextOutputGames;
    private javax.swing.JTextArea TextOutputMovies;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
